import DanceFloor as DF
import Figures as Fig
import SerialFigure

Floor = DF.DanceFloor('Marrie\'s Wedding',3)
newFloorMap = Floor.getDanceFloorMap()
print(Floor)
print('Full Turn')
Turn = Fig.SimpleFigure('dummy', 'empty')
Turn.loadFigure('1cRT')
Turn.Anchor = (1, 1)
DanceMove = Turn.DanceMove()
DCCripts = Turn.getCrips(Floor.getDanceFloorMap())
for i in range(len(DCCripts)):
    print(DCCripts[i])
Floor.doDanceMove(DanceMove,'Seriel')
print(Floor)

print('Rearange')
Floor.moveDancerbyPos((1, 1), (1.5, 0.75), newFloorMap)
Floor.moveDancerbyPos((2, 1), (-1, 0), newFloorMap)
Floor.moveDancerbyPos((1, 2), (0.5, -0.75), newFloorMap)
Floor.moveDancerbyPos((2, 2), (-1, 0), newFloorMap)
#print(newFloorMap)
Floor.setDanceFloorMap(newFloorMap)
# print(Floor)
# print('Reel')
# Reel = Fig.SimpleFigure('dummy', 'empty')
# Reel.loadFigure('H1DR')
# Reel.Anchor = (1, 1)
# DanceMove = Reel.DanceMove()
# print(DanceMove)
# DCCripts=Reel.getCrips(Floor.getDanceFloorMap())
# for i in range(len(DCCripts)):
#     print(DCCripts[i])
# Floor.doDanceMove(DanceMove)
# # newFloorMap = Floor.getDanceFloorMap()
# # for i in range(len(Reel.TransferCode)):
# #     Floor.moveDancerbyPos(DanceMove['Dancers'][i], DanceMove['Move'][i], newFloorMap)
# # Floor.setDanceFloorMap(newFloorMap)
# print(Floor)
#
# DanceMove = Reel.DanceMove()
# print(DanceMove)
# Floor.doDanceMove(DanceMove)
# # newFloorMap = Floor.getDanceFloorMap()
# # for i in range(len(Reel.TransferCode)):
# #     Floor.moveDancerbyPos(DanceMove['Dancers'][i], DanceMove['Move'][i], newFloorMap)
# # Floor.setDanceFloorMap(newFloorMap)
# print(Floor)
#
print(Floor)
print('Full Reel')
FullReel = SerialFigure.SerialFigure('dummy', 'empty')
FullReel.loadFigure('1DR')
FullReel.Anchor = (1, 1)
DanceMove = FullReel.DanceMove()
#print(DanceMove)
DCCripts = FullReel.getCrips(Floor.getDanceFloorMap())
for i in range(len(DCCripts)):
    print(DCCripts[i])
Floor.doDanceMove(DanceMove,'Seriel')
print(Floor)
print('First Reel')
Reel1 = Fig.SimpleFigure('dummy', 'empty')
Reel1.loadFigure('H1DR2c')
Reel1.Anchor = (1, 1)
print(Reel1.DanceMove())
DCCripts=Reel1.getCrips(Floor.getDanceFloorMap())
for i in range(len(DCCripts)):
    print(DCCripts[i])
Floor.doDanceMove(Reel1.DanceMove())
print(Floor)
print('Second Reel')
Reel2 = Fig.SimpleFigure('dummy', 'empty')
Reel2.loadFigure('H2DR3c')
Reel2.Anchor = (1, 1)
print(Reel2.DanceMove())
DCCripts=Reel2.getCrips(Floor.getDanceFloorMap())
for i in range(len(DCCripts)):
    print(DCCripts[i])
Floor.doDanceMove(Reel2.DanceMove())
print(Floor)
#print(Reel1.DanceMove())
print('Third Reel')
DCCripts=Reel1.getCrips(Floor.getDanceFloorMap())
for i in range(len(DCCripts)):
    print(DCCripts[i])
Floor.doDanceMove(Reel1.DanceMove())
print(Floor)
# #print(Reel2.DanceMove())
print('Forth Reel')
DCCripts=Reel2.getCrips(Floor.getDanceFloorMap())
for i in range(len(DCCripts)):
    print(DCCripts[i])
Floor.doDanceMove(Reel2.DanceMove())
print(Floor)
